### ISSUE TITLE
Errors in schema and on board silkscreen

### ISSUE THREAD

**Issue by jurajlutter** [alvaroalea/QL_QsoundQprint_clone#1]
There are some issues in schematics and in gerber:

- Schematics and gerber mentions 27512 EPROM while the correct one (as in BOM) is 2764
- Schematic has DIN connector upside down. Meaning: pin 1 should be 32, etc. A and B sides are OK.

**Comment by jurajlutter** [comment]
Another problem on PCB (found while I've been wondering why the left channel is silent): The signal leads to pins 2 and 4 on the jack J3. Instead, it should be routed to pin 2 and 5 (with pin "1" being GND).

**Comment by alvaroalea** [comment]
I put a note in the schematic about the 27512, and fix the pins of the Jack, still pending the DIN connector, I need to clear my symbol library first.

**Comment by alvaroalea** [comment]
I think I correct everything now, so I close the issue, feel free to open again if additional errors appear.
